#!/usr/bin/env bash
# Auto-generated skill trigger cache
# DO NOT EDIT - regenerated by scan-skill-triggers.sh
#
# Usage: source this file, then use SKILL_TRIGGERS associative array
# Example: for skill in "${!SKILL_TRIGGERS[@]}"; do ... done

declare -A SKILL_TRIGGERS=(
	["devtools:api"]="orpc|\\\\.contract\\\\.ts|\\\\.router\\\\.ts|\\\\.impl\\\\.ts|createProcedure"
	["devtools:better-auth"]="better-auth|betterAuth|authClient|auth\\\\.api"
	["devtools:rule-of-five"]="rule of five|5[- ]pass|convergence|iterative review|multi[- ]pass|review.*again"
	["devtools:tdd-typescript"]="tdd|test[- ]first|red[- ]green|write.*test|vitest|jest"
	["devtools:troubleshooting"]="help.*debug|how.*fix|why.*not working|troubleshoot|debug.*this"
	["devtools:zod"]="zod|z\\\\.object|z\\\\.string|z\\\\.number|z\\\\.enum|z\\\\.infer"
	["devtools:ast-grep"]="rename all|replace all.*with|refactor.*across|change all.*to|find and replace|ast-grep|sg |fix.*import|remove.*import|unused import|clean.*import|update.*import.*across|fix.*across.*files|fix all.*lint|remove.*from.*files|replace.*pattern|change.*syntax|migrate.*to|convert all|find all.*usage|where is.*used|show me all|audit.*code"
	["devtools:design-principles"]="dashboard|admin|admin.?panel|ui.?design|design.?system|spacing|typography|elevation|shadow|card|layout|Linear.?style|Notion.?style|Stripe.?style|Vercel.?style|clean.?ui|minimal.?design|minimalist|pixel.?perfect|polish|polished|crafted|SaaS|enterprise.?ui|professional.?ui|4px.?grid|border.?radius|design.?direction|color.?palette|dark.?mode|light.?mode|navigation|sidebar|monospace.?for.?data|data.?table|Jony.?Ive|precision"
	["devtools:drizzle"]="\\\\bdrizzle\\\\b|drizzle-orm|drizzle-kit|drizzle-zod|drizzle/pg-core|pgTable|mysqlTable|sqliteTable|\\\\$inferInsert|\\\\$inferSelect|text\\\\([\\\"']|varchar\\\\([\\\"']|boolean\\\\([\\\"']|timestamp\\\\([\\\"']|integer\\\\([\\\"']|serial\\\\([\\\"']|db\\\\.select|db\\\\.insert|db\\\\.update|db\\\\.delete|db\\\\.query|db\\\\.transaction|\\\\beq\\\\(|\\\\band\\\\(|\\\\bor\\\\(|\\\\bdesc\\\\(|\\\\basc\\\\(|\\\\blike\\\\(|\\\\bilike\\\\(|db:generate|db:migrate|db:push|db:studio|drizzle\\\\.config|\\\\.references\\\\(|onDelete.*cascade|relations\\\\(|(?i)create.*table|(?i)database.*schema|(?i)add.*column|(?i)run.*migration|(?i)generate.*migration|(?i)postgres.*query|(?i)sql.*query|(?i)foreign.*key|(?i)database.*index|(?i)orm.*query"
	["devtools:i18n"]="i18n|i18next|react-i18next|translation|translate|t\\\\(|useTranslation|Trans|internationali[zs]|locali[zs]|locale|multilingual|multi.?language|multiple.?languages|language.?switch|switch.?language|change.?language|fallbackLng|namespace|plurali[zs]|interpolation|RTL|right.?to.?left|LTR|left.?to.?right|language.?detection|translation.?file|\\.json.?translation"
	["devtools:motion"]="motion|framer|framer.?motion|animate|animation|animated|AnimatePresence|variants|transition|fade.?in|fade.?out|slide.?in|slide.?out|smooth.?transition|enter.?animation|exit.?animation|gesture|whileHover|whileTap|drag|draggable|spring.?animation|layout.?animation|stagger|orchestrat|keyframe|useAnimate|useMotionValue|useSpring|motion\\\\.div|motion\\\\.span"
	["devtools:playwright"]="playwright|playwrite|plawright|e2e|end[- ]?to[- ]?end|page[- ]?object|getByRole|getByLabel|getByTestId|getByText|browser.*test|test.*browser|integration.*test|test.*integration|web.*test|test.*web.*app|automat.*browser|browser.*automat|headless|headed.*test|toBeVisible|toHaveText|click.*fill|waitFor|\\\\.spec\\\\.ts|npx playwright|test\\\\.describe|functional.*test|ui.*test|test.*ui|user.*flow.*test|test.*user.*flow|smoke.*test|regression.*test|cross[- ]?browser"
	["devtools:recharts"]="recharts|chart|LineChart|BarChart|AreaChart|PieChart|ScatterChart|RadarChart|ComposedChart|ResponsiveContainer|graph|data.?viz|visualization|visualize.?data|plot|histogram|trend.?line|sparkline|metrics.?chart|analytics.?chart|dashboard.?chart|XAxis|YAxis|Tooltip|CartesianGrid|Legend|time.?series|display.?data|show.?data.?over.?time"
	["devtools:tanstack-start"]="tanstack[- ]?start|tanstack[- ]?router|@tanstack/(react-)?start|@tanstack/(react-)?router|createFileRoute|createRootRoute|createServerFn|serverFn|useLoaderData|useSearch|beforeLoad|file[- ]?based rout(e|ing)|route.*\\\\$.*param|dynamic route.*react|nested (layout|route)s?|layout route|ssr.*react|server[- ]?side render|streaming.*react|deferred (data|loading)|full[- ]?stack react|server (function|action)s?|rpc.*react|vinxi|nitro.*react|tankstack|tan stack|__root\\\\.tsx|routes/.*\\\\$|_authenticated"
	["devtools:vercel-design-guidelines"]="vercel.*design|vercel.*guidelines?|vercel.*best practices|review (my |the )?ui|review (my |the )?ux|audit (my |the )?(ui|ux|design)|check (my |the )?(ui|ux|design)|critique (my |the )?(ui|ux|design)|feedback.*(ui|ux|design)|check accessibility|accessibility audit|a11y (check|review|audit)|wcag (compliance|check|review)|aria.*review|keyboard (accessibility|navigation)|focus (management|trap|ring)|screen reader|design (system )?review|design guidelines|ui (best )?practices|ux (best )?practices|interface.*review|animation.*guidelines?|reduced[- ]?motion|loading state|form (validation|ux)|error (message|handling).*ux|hit target|color contrast|apca|(is|are) (my |the )?(ui|design|interface).*good|improve (my |the )?(ui|ux|design)|polish (my |the )?(ui|ux|design)|what('s| is) wrong.*(ui|ux|design)"
	["devtools:vitest"]="vitest|vite.*test|describe\\\\(|\\\\bit\\\\(|\\\\btest\\\\(|expect\\\\(|\\\\bmock|vi\\\\.fn|vi\\\\.mock|vi\\\\.spyOn|vi\\\\.stub|\\\\.test\\\\.ts|\\\\.spec\\\\.ts|unit.*test|test.*unit|write.*test|add.*test|create.*test|test.*file|test.*coverage|coverage.*report|beforeEach|afterEach|beforeAll|afterAll|toBe\\\\(|toEqual\\\\(|toHaveBeenCalled|toThrow|mockReturnValue|mockResolvedValue|mockImplementation|bun.*test|run.*test|test.*pass|test.*fail|assert|spy|fake.*timer|useFakeTimers"
	["flow:flow:analyze"]="analyze codebase|analyze project|code analysis|audit code|review structure"
	["flow:guides:analysis"]="analyze|analysis|evaluate|assess|review structure|code quality"
	["flow:guides:optimization"]="optimize|optimization|improve|refactor|performance|technical debt"
	["flow:guides:patterns"]="workflow|process|pattern|template|flow|productivity"
	["flow:flow:init"]="init flow|initialize flow|setup flow|start flow"
	["flow:flow:status"]="flow status|workflow status|check status|show progress"
	["flow:flow:suggest"]="suggest improvements|get suggestions|improvement recommendations|what to improve"
	["flow:workflow:complete"]="complete workflow|finish workflow|end workflow|done with workflow"
	["flow:workflow:pause"]="pause workflow|stop workflow|suspend workflow"
	["flow:workflow:start"]="start workflow|begin workflow|new workflow|create workflow"
)

# Generated at: 2026-01-15T10:22:50Z
# Skill count: ${#SKILL_TRIGGERS[@]}
